// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_IOS']!,
    appId: '1:118660317591:ios:8a7db5121ade2948c144d2',
    messagingSenderId: '118660317591',
    projectId: 'mypetwatchapplication',
    storageBucket: 'mypetwatchapplication.firebasestorage.app',
    iosClientId: '118660317591-lb303jd1kr4iessltjm8a1favls26c6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPetWatch',
  );

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_WEB']!,
    appId: '1:118660317591:web:510523d1fb7b05f9c144d2',
    messagingSenderId: '118660317591',
    projectId: 'mypetwatchapplication',
    authDomain: 'mypetwatchapplication.firebaseapp.com',
    storageBucket: 'mypetwatchapplication.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_ANDROID']!,
    appId: '1:118660317591:android:f03d6951dad39237c144d2',
    messagingSenderId: '118660317591',
    projectId: 'mypetwatchapplication',
    storageBucket: 'mypetwatchapplication.firebasestorage.app',
  );

}